ruleArchive: latest
policies:
  - IBM_Accessibility
failLevels:
  - violation
  - potentialviolation
reportLevels:
  - violation
  - potentialviolation
  - recommendation
  - potentialrecommendation
  - manual
outputFormat:
  - json
label:
  - master
outputFilenameTimestamp: false
baselineFolder: test/baselines
cacheFolder: /tmp/accessibility-checker
outputFolder: results
