name: Docs Ally Tests- OL API

on:
  push:
    branches:
      - main
  pull_request:
 
jobs:
  openliberty-api:
    runs-on: ubuntu-latest
    container: cypress/included:13.9.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup previous results
        run: rm -rf /__w/Ally-docs/Ally-docs/cypress-docs/results/*

      - name: Cleanup Cypress Cache
        run: rm -rf ~/.cache/Cypress

      - name: Run first test file
        run: |
          cypress run --browser chrome --headed \
          --env JDK_VERSION="1.8.0_311" \
          --config-file /__w/Ally-docs/Ally-docs/cypress-docs/cypress.config.js \
          --spec "/__w/Ally-docs/Ally-docs/cypress-docs/cypress/e2e/gha.cy.js" \
          --reporter json --reporter-options output=/__w/Ally-docs/Ally-docs/cypress-docs/results/summary.json

      - name: Debug - List files
        run: ls -R /__w/Ally-docs/Ally-docs

      - name: Debug - Cypress Logs
        run: cat /__w/Ally-docs/Ally-docs/cypress-docs/results/summary.json || echo "No summary file found"

      - name: Upload Summary Results
        if: success() 
        uses: actions/upload-artifact@v4
        with:
          name: Summary File
          path: /__w/Ally-docs/Ally-docs/cypress-docs/results/summary.json
          if-no-files-found: warn      
          include-hidden-files: true 
