name: Docs Ally Tests- OL API

on:
  push:
    branches:
      - main
  pull_request:
 
jobs:
  openliberty-api:
    runs-on: ubuntu-latest
    container: cypress/included:13.9.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug - List files
        run: ls -R ${{ github.workspace }}  
      # - name: Clear cache
      #   run: rm -rf ~/.npm ~/.cache/pip node_modules   
      - name: Run first test file
        run: cypress run --browser chrome --env JDK_VERSION="1.8.0_311" --config-file /__w/Ally-docs/Ally-docs/cypress-docs/cypress.config.js --spec "/__w/Ally-docs/Ally-docs/cypress-docs/cypress/e2e/gha.cy.js"
    #   - name: Wait for File Creation
    #     run: |
    #       while [ ! -f /__w/Ally-docs/Ally-docs/cypress-docs/results/summary.json ]; do
    #         echo "Waiting for summary.json to be created..."
    #         sleep 1
    #       done
    #       echo "summary.json is now available."  
      # - name: Upload Compliance Results
      #   if: success() 
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ol_api_overview2
      #     path: /__w/Ally-docs/Ally-docs/cypress-docs/results/OL_API/ol_api_overview2.json
      #     if-no-files-found: warn
      # - name: Upload Compliance Results
      #   if: success() 
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ol_api_package1
      #     path: /__w/Ally-docs/Ally-docs/cypress-docs/results/OL_API/ol_api_package1.json
      #     if-no-files-found: warn    
      # - name: Upload Compliance Results
      #   if: success() 
      #   uses: actions/upload-artifact@v4
      #   with:
      #       name: ol_api_package2
      #       path: /__w/Ally-docs/Ally-docs/cypress-docs/results/OL_API/ol_api_package2.json
      #       if-no-files-found: warn    
      - name: Upload Summary Results
        if: success() 
        uses: actions/upload-artifact@v4
        with:
            name: Summary File
            path: /__w/Ally-docs/Ally-docs/cypress-docs/results/summary*.json
            if-no-files-found: warn      
            include-hidden-files: true      
  
