name: Docs Ally Tests- OL API

on:
  push:
    branches:
      - main
  pull_request:
 
jobs:
  openliberty-api:
    runs-on: ubuntu-latest
    container: cypress/included:13.9.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Run Cypress test
      - name: Run first test file
        run: cypress run --browser chrome --env JDK_VERSION="1.8.0_311" --config-file ${{ github.workspace }}/cypress-docs/cypress.config.js --spec "${{ github.workspace }}/cypress-docs/cypress/e2e/gha.cy.js"

      # Debug: Verify all files after tests run
      - name: Debug - List all files in workspace
        run: ls -R ${{ github.workspace }}

      # Debug: Check if summary files exist
      - name: Debug - Check summary files
        run: ls -R ${{ github.workspace }}/cypress-docs/results || echo "No summary files found!"

      # Upload test summary files if they exist
      - name: Upload Summary Results
        if: success()
        uses: actions/upload-artifact@v4
        with:
            name: Summary File
            path: ${{ github.workspace }}/cypress-docs/results/summary*.json
            if-no-files-found: warn      
            include-hidden-files: true  
