name: Create Automatic PR for release blogs

on:
  push:
    branches:
      - '**-post'
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "Creating PR from $branch_name to draft"
          gh pr create \
            --head "$branch_name" \
            --base "draft" \
            --title "Automated PR: Merge $branch_name into draft" \
            --body "This PR was created automatically by GitHub Actions to merge changes from $branch_name into draft." \
            || echo "PR creation failed or PR already exists"
