name: Create automatic PRs

on:
  pull_request:
    types: [closed]
    branches:
      - staging
  workflow_dispatch:    

jobs:
  create-pr:
    if: |
      github.event.pull_request.merged == true && 
      (
        startsWith(github.event.pull_request.head.ref, '25.') ||
        endsWith(github.event.pull_request.head.ref, '-beta')
      )  
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: diillson/auto-pull-request@v1.0.1
      with:
        source_branch: "${{ github.event.pull_request.head.ref }}"                                 # If "", default: triggered branch
        destination_branch: "draft"                      # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into draft" # Title of pull request
        pr_body: "This is a sample PR"
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        pr_draft: true                                    # Creates pull request as draft
        pr_allow_empty: true                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}      # If blank, default: secrets.GITHUB_TOKEN


      
