name: Create Automatic PR for release blogs

on:
  push:
    branches:
      - '**-post'
  workflow_dispatch:

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create PR to draft for release blogs
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: draft
          title: "Automatic PR from ${{ github.ref_name }} to draft"
          body: "This PR is created as updates are made to release blog ${{ github.ref_name }}"
          draft: true    
