name: Rebase Check

on:
  pull_request:
    branches:
      - staging
      - draft

jobs:
  rebase-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to allow rebase checks

      - name: Set variables
        id: vars
        run: |
          echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "FEATURE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Post comparison link if base is staging or main
        uses: actions/github-script@v7
        with:
          script: |
            const base = process.env.BASE_BRANCH;
            const head = process.env.FEATURE_BRANCH;

            if (base === 'staging' || base === 'main') {
              const compareUrl = `https://github.com/navaneethsnair1/Ally-docs/compare/${base}..${head}`;
              await github.rest.issues.createComment({
                owner: context.repo.owner 
                repo: 'Ally-docs',
                issue_number: context.payload.pull_request.number,
                body: `**Compare your changes here:**\n${compareUrl}\nEnsure the changes are identical to the desired changes. If not, please rebase ${head} onto ${base}`
              });
            }

      - name: Check if PR can be rebased cleanly
        id: rebase-check
        run: |
          git fetch origin $BASE_BRANCH
          if git rebase --no-commit --no-ff origin/$BASE_BRANCH; then
            echo "REBASE_POSSIBLE=true" >> $GITHUB_ENV
            git rebase --abort
          else
            echo "REBASE_POSSIBLE=false" >> $GITHUB_ENV
            git rebase --abort
          fi

      - name: Comment rebase possibility
        uses: actions/github-script@v7
        with:
          script: |
            const rebasePossible = process.env.REBASE_POSSIBLE;
            const prNumber = context.payload.pull_request.number;

            let msg = '';
            if (rebasePossible === 'true') {
              msg = 'This PR can be rebased cleanly onto its base branch.';
            } else {
              msg = 'This PR **cannot** be rebased cleanly. Please resolve conflicts.';
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner ,
              repo: 'Ally-docs',
              issue_number: prNumber,
              body: msg
            });
