name: Rebase Check

on:
  pull_request:
    branches:
      - staging
      - draft

jobs:
  rebase-check:
    runs-on: ubuntu-latest
    steps:
      - name: Post '..' comparison link to verify changes are identical to normal comparison
        uses: actions/github-script@v7
        with:
          script: |
            const compareUrl = `https://github.com/navaneethsnair1/Ally-docs/compare/${{ github.base_ref }}..${{ github.head_ref }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: 'Ally-docs',
              issue_number: context.payload.pull_request.number,
              body: |
                **Compare your changes here:**\n${compareUrl}

                Ensure the changes are identical to the desired changes. 
                If not, please resolve merge conflicts (if any) and rebase '${{ github.head_ref }}' onto '${{ github.base_ref }}'
            });

