name: Run Prohibited terms PR checker

on:
  pull_request:
    branches:
      - staging
      - main

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout updated branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Example Status Check
        run: |
          echo "✅ Running status checks..."
