name: Run Prohibited terms PR checker

on:
  pull_request:
    branches:
      - draft
      - staging

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout updated branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up PAT authentication
        env:
          PAT: ${{ secrets.Rebase_PAT }}
        run: |
          git remote set-url origin https://${PAT}@github.com/${{ github.repository }}.git      

      - name: Example Status Check
        run: |
          echo "✅ Running status checks..."
